"""
Regenerate the translation progress table in README.md.

One row per scene: the scene id, how many of its lines have an English
translation, and the three speakers with the most lines in it. Scenes that are not
completely translated come first, least translated first, then the finished ones
by the number in the scene id (the evs_/hmn_/... prefix is ignored); ties are
broken the same way. Speakers come
from the 《speaker》 prefix of ja.json values; narration has no prefix and is not
counted. Names are shown in English where the glossary (names/en.json) has one.

The table lives between the PROGRESS markers in README.md, which are added at
the end of the file the first time the script runs. Nothing outside the markers
is touched.

Usage:
    PYTHONUTF8=1 python tools_en/readme_progress.py
    PYTHONUTF8=1 python tools_en/readme_progress.py --check    # exit 1 if README.md is stale
"""

import argparse
import collections
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths

README_PATH = os.path.join(paths.REPO_ROOT, "README.md")
START = "<!-- PROGRESS:START (generated by tools_en/readme_progress.py, do not edit) -->"
END = "<!-- PROGRESS:END -->"
HEADING = "## Translation progress"

SPEAKER = re.compile(r"^《([^》]*)》")
TOP_SPEAKERS = 3
BAR_WIDTH = 20


def display_name(speaker, glossary):
    name = glossary.get(speaker) or speaker
    return name.replace("|", "\\|").replace("<", "&lt;").replace(">", "&gt;")


def scene_number(scene_id):
    return int(scene_id.split("_", 1)[1])


def progress_bar(translated, count):
    # Floored, so the bar only reads full when the scene really is complete.
    filled = translated * BAR_WIDTH // count if count else 0
    return "`[" + "#" * filled + "-" * (BAR_WIDTH - filled) + "]`"


def scene_row(scene_id, glossary):
    scene_dir = os.path.join(paths.NOVELS_DIR, scene_id)
    ja = paths.load_json(os.path.join(scene_dir, "ja.json"))
    en = paths.load_json(os.path.join(scene_dir, "en.json"))

    translated = sum(1 for v in en.values() if v)
    speakers = collections.Counter()
    for value in ja.values():
        m = SPEAKER.match(value)
        if m and m.group(1):
            speakers[display_name(m.group(1), glossary)] += 1

    # most_common keeps first-seen order among equal counts, so ties are stable.
    top = ", ".join(f"{name} ({count})" for name, count in speakers.most_common(TOP_SPEAKERS))
    return translated, len(en), top


def build_table():
    glossary = paths.load_json(os.path.join(paths.NAMES_DIR, "en.json"), default={})

    rows = []
    done = total = 0
    for scene_id in paths.scene_dirs():
        translated, count, top = scene_row(scene_id, glossary)
        done += translated
        total += count
        percent = round(100 * translated / count) if count else 0
        link = f"[{scene_id}](translations/novels/{scene_id}/en.json)"
        complete = translated == count
        ratio = translated / count if count else 1
        bar = progress_bar(translated, count)
        text = f"| {link} | {translated}/{count} ({percent}%)<br>{bar} | {top} |"
        rows.append(((complete, 0 if complete else ratio, scene_number(scene_id), scene_id), text))
    rows.sort(key=lambda r: r[0])
    rows = [r[1] for r in rows]

    overall = round(100 * done / total, 1) if total else 0
    lines = [
        f"{done:,} of {total:,} lines translated ({overall}%) across {len(rows)} scenes.",
        "",
        "| filename | progress | characters |",
        "|---|---|---|",
    ]
    return "\n".join(lines + rows)


def render(readme):
    block = f"{START}\n{build_table()}\n{END}"
    if START in readme and END in readme:
        head, rest = readme.split(START, 1)
        _, tail = rest.split(END, 1)
        return head + block + tail
    return readme.rstrip("\n") + f"\n\n{HEADING}\n\n{block}\n"


def main():
    ap = argparse.ArgumentParser(description="Regenerate the progress table in README.md.")
    ap.add_argument("--check", action="store_true", help="exit 1 if README.md would change")
    args = ap.parse_args()

    with open(README_PATH, "r", encoding="utf-8") as fh:
        current = fh.read()
    updated = render(current)

    if updated == current:
        print("README.md progress table is up to date.")
        return
    if args.check:
        print("README.md progress table is stale. Run tools_en/readme_progress.py.")
        sys.exit(1)

    with open(README_PATH, "w", encoding="utf-8") as fh:
        fh.write(updated)
    print("README.md progress table updated.")


if __name__ == "__main__":
    main()
